"""Carrying-leg round: G7 (5) - THE RUNNER REGISTER for the FF_EXIT_LEG_* flip
(carryleg_prereg.txt section 10; design carryleg_part1.txt section 7 (5); the shape of
outputs/flip_runner_register.txt). Writes outputs/carryleg_flip_register.txt.

THE FLIP: FF_EXIT_LEG_MODE 0 -> 2, FF_EXIT_LEG_SERVED 0 -> 1 (cfv + the agents.py
missing-value defaults; EXIT_LEG_MODE_JUNK 1 -> 2). FF_EXIT_LEG_HOLD stays 0.

RULE. A run is FLIP-SAFE iff it sets FF_EXIT_LEG_MODE and FF_EXIT_LEG_SERVED explicitly
(HOLD did not move). Every other simulation run launched from this checkout after the flip
measures MODE 2 + SERVED 1 instead of the pre-flip 0/0 - SILENT-CHANGE - unless a
validator refuses it: this round's own pools (outputs/_cl_pool.sh + _cl_validate.py) FAIL
LOUDLY on any pre-flip queue, because every sidecar carries the source sha256 (check (6),
SOURCE MISMATCH refuses the pool start) and the recorded switches (check (3)).

SCANNED (deterministic; os.listdir, NON-recursive; the quarantine entry skipped by name):
  queue files   outputs/*queue*.txt - every job line (kind|tag|repo|...|extra): FLIP-SAFE
                iff its extra sets both flipped keys; the repo column is reported, since a
                line whose repo is ANOTHER worktree is unaffected by this checkout's flip
  runners       outputs/*.sh, outputs/*.ps1 - classified by what they launch (a harness,
                the campaign, evaluate_scenarios, pytest, a pool) and whether the file
                itself names both flipped keys
  entry points  the repo root *.py that build WildFireModel, and the tests/ suite (G6b)
Pure text; imports nothing from the model.

usage: .venv/Scripts/python.exe -B outputs/_cl_flip_register.py
"""
import collections
import os
import re
import sys

sys.dont_write_bytecode = True
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(HERE, "carryleg_flip_register.txt")
QUAR = "_firemech_rewound_20260914"
KEYS = ("FF_EXIT_LEG_MODE", "FF_EXIT_LEG_SERVED")
MAIN = "e:/projects/sas"
LAUNCH = (("_ffr_harness", "harness"), ("_fm2_probe_harness", "crn-harness"), ("_cl_obs", "cl-sidecar"),
          ("_cl_probe", "cl-probe"), ("_rblatch_campaign2", "rb-campaign"), ("evaluate_scenarios", "evaluate"),
          ("pytest", "pytest"), ("_pool.sh", "pool"), ("serve_dashboard", "dashboard"))
CL_OWN = re.compile(r"^_cl_")
# a file "runs the model" if it imports it (or a harness / the campaign / evaluate_scenarios)
SIM_RE = re.compile(r"^\s*(from|import)\s+(wildfire_model|evaluate_scenarios|_ffr_harness|_rblatch_campaign2)\b"
                    r"|runpy\.run_path\([^)]*(_ffr_harness|_fm2_probe_harness)", re.M)
NOT_ENTRY = {"wildfire_model.py", "common_fixed_variables.py", "agents.py"}


def read(path):
    with open(path, "rb") as f:
        return f.read().decode("utf-8", "replace").replace("\r", "")


def names(d):
    return sorted(n for n in os.listdir(d) if n != QUAR)


def sets_both(text):
    return all(re.search(r"--set\s+%s=" % k, text) or re.search(r"\b%s\s*=" % k, text) for k in KEYS)


def main():
    out = []
    say = out.append
    say("CARRYING-LEG FLIP RUNNER REGISTER - tooling whose meaning changes at the FF_EXIT_LEG_* flip")
    say("Generated by outputs/_cl_flip_register.py (carryleg_prereg.txt section 10, G7 (5)).")
    say("")
    say("THE FLIP: FF_EXIT_LEG_MODE 0 -> 2, FF_EXIT_LEG_SERVED 0 -> 1 (cfv and the agents.py")
    say("missing-value defaults; EXIT_LEG_MODE_JUNK 1 -> 2). FF_EXIT_LEG_HOLD is unchanged (0).")
    say("RULE: FLIP-SAFE iff a run sets FF_EXIT_LEG_MODE and FF_EXIT_LEG_SERVED explicitly; otherwise")
    say("a run launched from this checkout after the flip measures MODE 2 + SERVED 1 - SILENT-CHANGE -")
    say("except where a validator refuses it (this round's _cl_ pools: FAILS-LOUDLY, source sha256 +")
    say("recorded switches in every sidecar). Lines whose repo column is another worktree are unaffected.")
    say("")
    # ---- queue files
    qfiles = [n for n in names(HERE) if re.search(r"queue.*\.txt$", n)]
    rows = []
    for n in qfiles:
        safe = silent = other_repo = 0
        for ln in read(os.path.join(HERE, n)).split("\n"):
            if not ln.strip() or ln.startswith("#") or ln.count("|") < 7:
                continue
            parts = ln.split("|", 7)
            repo, extra = parts[2].replace("\\", "/").rstrip("/").lower(), parts[7]
            if repo and repo != MAIN and parts[0] == "ff":
                other_repo += 1
            elif sets_both(extra):
                safe += 1
            else:
                silent += 1
        if safe + silent + other_repo == 0:
            cls = "NO-JOB-LINES"          # not the kind|tag|repo|... shape (an older queue format)
        elif CL_OWN.match(n) and silent:
            cls = "FAILS-LOUDLY"
        else:
            cls = "SILENT-CHANGE" if silent else "FLIP-SAFE"
        rows.append((n, safe, silent, other_repo, cls))
    tot = collections.Counter()
    say("A. QUEUE FILES (outputs/*queue*.txt, %d files): job lines FLIP-SAFE / SILENT-CHANGE / other repo" % len(rows))
    for n, a, b, c, cls in rows:
        tot["safe"] += a
        tot["silent"] += b
        tot["other"] += c
        tot[cls] += 1
        say("  %-44s %4d / %4d / %4d  %s" % (n, a, b, c, cls))
    say("  TOTAL lines: FLIP-SAFE %d, SILENT-CHANGE %d (of which in this round's _cl_ queues: loud), other repo %d;"
        % (tot["safe"], tot["silent"], tot["other"]))
    say("  files: FLIP-SAFE %d, SILENT-CHANGE %d, FAILS-LOUDLY %d, NO-JOB-LINES %d (older formats: read them"
        % (tot["FLIP-SAFE"], tot["SILENT-CHANGE"], tot["FAILS-LOUDLY"], tot["NO-JOB-LINES"]))
    say("  by hand before any re-run)")
    say("")
    # ---- simulation python files (outputs/, non-recursive): they run the model directly or
    # through a harness/campaign/evaluate entry
    simpy = {}
    for n in names(HERE):
        if n.endswith(".py") and not CL_OWN.match(n):
            text = read(os.path.join(HERE, n))
            if SIM_RE.search(text):
                simpy[n] = sets_both(text)
    for n in names(ROOT):
        if n.endswith(".py") and SIM_RE.search(read(os.path.join(ROOT, n))) and n not in NOT_ENTRY:
            simpy.setdefault(n, False)
    # ---- runners
    runners = [n for n in names(HERE) if n.endswith((".sh", ".ps1"))]
    say("B. RUNNERS (outputs/*.sh, outputs/*.ps1, %d files)" % len(runners))
    cnt = collections.Counter()
    for n in runners:
        text = read(os.path.join(HERE, n))
        kinds = [k for pat, k in LAUNCH if pat in text]
        for py in sorted(set(re.findall(r"([A-Za-z0-9_./-]+\.py)\b", text))):
            base = os.path.basename(py)
            if base in simpy and base not in kinds:
                kinds.append(base)
        if not kinds:
            cls = "NOT-A-SIMULATION"
        elif CL_OWN.match(n):
            cls = "FAILS-LOUDLY" if "pool" in n else ("G6b-RUNNER" if "pytest" in n else "FAILS-LOUDLY")
        elif sets_both(text):
            cls = "FLIP-SAFE"
        else:
            cls = "SILENT-CHANGE"
        cnt[cls] += 1
        say("  %-40s %-18s %s" % (n, cls, ",".join(kinds) or "-"))
    say("  " + ", ".join("%s %d" % kv for kv in sorted(cnt.items())))
    say("")
    # ---- entry points
    say("C. ENTRY POINTS AND THE SUITE")
    for n in names(ROOT):
        if n.endswith(".py") and n not in NOT_ENTRY and SIM_RE.search(read(os.path.join(ROOT, n))):
            say("  %-40s runs the model -> the SHIPPED values (intended: this is the ship)" % n)
    say("  tests/ (the suite)                       G6b on the flipped tree (_cl_pytest.sh VARIANT=post)")
    say("")
    outpy = sorted((n, s) for n, s in simpy.items() if os.path.exists(os.path.join(HERE, n)))
    say("D. PYTHON IN outputs/ THAT RUNS THE MODEL (non-recursive, this round's _cl_ tools apart: %d files)" % len(outpy))
    say("  FLIP-SAFE (names both flipped keys) %d, SILENT-CHANGE %d:" % (sum(1 for _n, s in outpy if s),
                                                                       sum(1 for _n, s in outpy if not s)))
    for n, s in outpy:
        say("  %-44s %s" % (n, "FLIP-SAFE" if s else "SILENT-CHANGE"))
    say("  (the harnesses _ffr_harness.py / _fm2_probe_harness.py / _rblatch_campaign2.py pass the queue")
    say("   line's --set through; their meaning is the line's, section A)")
    say("")
    # lines that measured SERVED at MODE 0 (SERVED set non-zero, MODE unset or 0)
    pre_enf = collections.Counter()
    for n in qfiles:
        for ln in read(os.path.join(HERE, n)).split("\n"):
            if ln.count("|") < 7 or ln.startswith("#"):
                continue
            extra = ln.split("|", 7)[7]
            sv = re.search(r"--set\s+FF_EXIT_LEG_SERVED=(\S+)", extra)
            md = re.search(r"--set\s+FF_EXIT_LEG_MODE=(\S+)", extra)
            if sv and sv.group(1) not in ("0", "0.0", "False") and (md is None or md.group(1) in ("0", "0.0", "False")):
                pre_enf[n] += 1
    say("E. RUNS THAT MEASURED SERVED AT MODE 0 - REPRODUCIBLE ONLY BEFORE THE ENFORCEMENT")
    say("  Ruling S2 (2026-09-27) enforces SERVED to 0 whenever MODE is 0 (agents.ff_exit_leg_served). A")
    say("  line that set FF_EXIT_LEG_SERVED non-zero with MODE unset (pre-flip: 0) or 0 measured SERVED")
    say("  at MODE 0; at HEAD no --set combination reproduces it (MODE unset -> 2 since the flip;")
    say("  MODE=0 -> SERVED forced off). Reproduce such a run only on a checkout <= 52da783 (the D-9")
    say("  probe ran at 108a0ad). Queue lines of that kind:")
    for n in sorted(pre_enf):
        say("  %-44s %4d" % (n, pre_enf[n]))
    say("  (+ the rbgate shards clGSNa/b/c/s, whose SERVED=1 rides in the rb extra field: counted above)")
    say("")
    say("WHAT TO DO BEFORE RE-RUNNING ANY SILENT-CHANGE LINE: add --set FF_EXIT_LEG_MODE=0")
    say("--set FF_EXIT_LEG_SERVED=0 to reproduce its recorded pre-flip meaning. The recorded runs")
    say("themselves are unaffected (they are files); only a re-run changes meaning.")
    with open(OUT + ".tmp", "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    os.replace(OUT + ".tmp", OUT)
    print("wrote %s: %d queue files (%d SILENT-CHANGE lines), %d runners" % (
        os.path.basename(OUT), len(rows), tot["silent"], len(runners)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
