"""MVG round: THE RUNNER REGISTER for the movement flip (outputs/urgency_part1d.txt 1d.6.3 THE FLIP; the maintainer's
ruling 2026-10-07; the shape of outputs/carryleg_flip_register.txt, generated by outputs/_cl_flip_register.py, which
this file adapts). Writes outputs/movement_flip_register.txt.

THE FLIP: FF_APPROACH_PATH 0 -> 1 and FF_RETREAT_KEEP_APPROACH 0 -> 1 (common_fixed_variables.py), and their accessors
from "on only on an exact 1" (missing = off) to "off only on an exact 0" (missing = ON). FF_FIX_STRANDING_GUARD is
unchanged (1).

RULE. A run is FLIP-SAFE iff it sets FF_APPROACH_PATH and FF_RETREAT_KEEP_APPROACH explicitly. Every other simulation
run launched from this checkout after the flip measures the fixes ON (behind the guard), where before the flip it
measured them off - or, before the fixes existed (main up to a20a2ef5), measured today's movement - SILENT-CHANGE -
unless a validator refuses it: this round's own analyzer (outputs/_mvg_analyze.py prov_run) refuses a run whose
recorded effective switches differ from its queue line's (FAILS-LOUDLY). Queues written at or after the flip
(outputs/_mvg_q_flip.jsonl, outputs/_mvg_q_ist.jsonl) already measure the shipped values: POST-FLIP.

SCANNED (deterministic; os.listdir, NON-recursive; the quarantine entry skipped by name):
  queue files   outputs/*queue*.txt - every job line (kind|tag|repo|...|extra): FLIP-SAFE iff its extra sets both
                flipped keys; a line whose repo is ANOTHER worktree (neither this one nor the main checkout
                E:/Projects/SAS, which carries the flip after the merge) is unaffected
                outputs/*.jsonl with pool lines ({"name", "argv", ...}): FLIP-SAFE iff the argv sets both keys
  runners       outputs/*.sh, outputs/*.ps1 - classified by what they launch and whether they name both keys
  entry points  the repo root *.py that build WildFireModel, and the tests/ suite
Pure text; imports nothing from the model.

usage: .venv/Scripts/python.exe -B outputs/_mvg_flip_register.py
"""
import collections
import json
import os
import re
import sys

sys.dont_write_bytecode = True
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(HERE, "movement_flip_register.txt")
QUAR = "_firemech_rewound_20260914"
KEYS = ("FF_APPROACH_PATH", "FF_RETREAT_KEEP_APPROACH")
THIS_REPO = os.path.normcase(os.path.normpath(ROOT))
# the checkouts that carry the flip: this worktree, and the main checkout once main is fast-forwarded to it
MAIN = os.path.normcase(os.path.normpath(r"E:\Projects\SAS"))
AFFECTED = {THIS_REPO, MAIN}
LAUNCH = (("_ffr_harness", "harness"), ("_fm2_probe_harness", "crn-harness"), ("_mvg_probe", "mvg-probe"),
          ("_ud_probe", "ud-probe"), ("_ut_probe", "ut-probe"), ("_rblatch_campaign2", "rb-campaign"),
          ("evaluate_scenarios", "evaluate"), ("pytest", "pytest"), ("_pool", "pool"),
          ("serve_dashboard", "dashboard"))
MVG_LOUD = re.compile(r"^_mvg_q_(w1|w2|w3|port|smoke|structure)\.jsonl$")
POST_FLIP = {"_mvg_q_flip.jsonl", "_mvg_q_ist.jsonl"}
SIM_RE = re.compile(r"^\s*(from|import)\s+(wildfire_model|evaluate_scenarios|_ffr_harness|_rblatch_campaign2)\b"
                    r"|runpy\.run_path\([^)]*(_ffr_harness|_fm2_probe_harness|_ut_probe|_sd_probe)", re.M)
NOT_ENTRY = {"wildfire_model.py", "common_fixed_variables.py", "agents.py"}


def read(path):
    with open(path, "rb") as f:
        return f.read().decode("utf-8", "replace").replace("\r", "")


def names(d):
    return sorted(n for n in os.listdir(d) if n != QUAR)


def sets_both(text):
    return all(re.search(r"--set\s+%s=" % k, text) or re.search(r"\b%s\s*=" % k, text) for k in KEYS)


def argv_sets_both(argv):
    sets = {argv[i + 1].split("=", 1)[0] for i, a in enumerate(argv[:-1]) if a == "--set"}
    return all(k in sets for k in KEYS)


def argv_repo(argv):
    if "--repo" in argv:
        return os.path.normcase(os.path.normpath(argv[argv.index("--repo") + 1]))
    return None


def main():
    out = []
    say = out.append
    say("MOVEMENT FLIP RUNNER REGISTER - tooling whose meaning changes at the FF_APPROACH_PATH /")
    say("FF_RETREAT_KEEP_APPROACH flip. Generated by outputs/_mvg_flip_register.py (the MVG round's flip, 2026-10-07).")
    say("")
    say("THE FLIP: FF_APPROACH_PATH 0 -> 1, FF_RETREAT_KEEP_APPROACH 0 -> 1, and a MISSING switch now reads ON (the")
    say("accessors are 'off only on an exact 0'). FF_FIX_STRANDING_GUARD is unchanged (1).")
    say("RULE: FLIP-SAFE iff a run sets both fix switches explicitly; otherwise a run launched from this checkout after")
    say("the flip measures the guarded fixes ON - SILENT-CHANGE - except where a validator refuses it (this round's")
    say("analyzer refuses a run whose recorded switches differ from its line: FAILS-LOUDLY). POST-FLIP queues were")
    say("written for the flipped tree. Lines whose repo is another worktree are unaffected by this checkout's flip.")
    say("")
    # ---- A. pipe-format queue files
    qfiles = [n for n in names(HERE) if re.search(r"queue.*\.txt$", n)]
    rows, tot = [], collections.Counter()
    for n in qfiles:
        safe = silent = other_repo = 0
        for ln in read(os.path.join(HERE, n)).split("\n"):
            if not ln.strip() or ln.startswith("#") or ln.count("|") < 7:
                continue
            parts = ln.split("|", 7)
            repo, extra = parts[2], parts[7]
            if repo and os.path.normcase(os.path.normpath(repo)) not in AFFECTED and parts[0] == "ff":
                other_repo += 1
            elif sets_both(extra):
                safe += 1
            else:
                silent += 1
        cls = ("NO-JOB-LINES" if safe + silent + other_repo == 0
               else "SILENT-CHANGE" if silent else "FLIP-SAFE" if safe else "OTHER-REPO")
        rows.append((n, safe, silent, other_repo, cls))
    say("A. QUEUE FILES (outputs/*queue*.txt, %d files): job lines FLIP-SAFE / SILENT-CHANGE / other repo" % len(rows))
    for n, a, b, c, cls in rows:
        tot["safe"] += a
        tot["silent"] += b
        tot["other"] += c
        tot[cls] += 1
        say("  %-44s %4d / %4d / %4d  %s" % (n, a, b, c, cls))
    say("  TOTAL lines: FLIP-SAFE %d, SILENT-CHANGE %d, other repo %d; files: FLIP-SAFE %d, SILENT-CHANGE %d,"
        " OTHER-REPO %d," % (tot["safe"], tot["silent"], tot["other"], tot["FLIP-SAFE"], tot["SILENT-CHANGE"],
                            tot["OTHER-REPO"]))
    say("  NO-JOB-LINES %d (older formats: read them by hand before any re-run)" % tot["NO-JOB-LINES"])
    say("")
    # ---- A2. JSONL pool queues
    jrows, jt = [], collections.Counter()
    for n in names(HERE):
        if not n.endswith(".jsonl"):
            continue
        safe = silent = other_repo = 0
        bad = False
        for ln in read(os.path.join(HERE, n)).split("\n"):
            if not ln.strip():
                continue
            try:
                d = json.loads(ln)
            except ValueError:
                bad = True
                break
            argv = d.get("argv") if isinstance(d, dict) else None
            if not isinstance(argv, list):
                bad = True
                break
            repo = argv_repo(argv)
            if repo is not None and repo not in AFFECTED:
                other_repo += 1
            elif argv_sets_both(argv):
                safe += 1
            else:
                silent += 1
        if bad or safe + silent + other_repo == 0:
            continue
        if n in POST_FLIP:
            cls = "POST-FLIP"
        elif MVG_LOUD.match(n) and silent:
            cls = "FAILS-LOUDLY"
        else:
            cls = "SILENT-CHANGE" if silent else "FLIP-SAFE" if safe else "OTHER-REPO"
        jrows.append((n, safe, silent, other_repo, cls))
    say("A2. POOL QUEUES (outputs/*.jsonl with argv lines, %d files): lines FLIP-SAFE / SILENT-CHANGE / other repo"
        % len(jrows))
    for n, a, b, c, cls in jrows:
        jt[cls] += 1
        say("  %-44s %4d / %4d / %4d  %s" % (n, a, b, c, cls))
    say("  files: " + ", ".join("%s %d" % kv for kv in sorted(jt.items())))
    say("  FAILS-LOUDLY: the MVG round's own queues (W1 / W2 / W3, port, smoke, structure) - outputs/_mvg_analyze.py")
    say("  refuses a run whose recorded effective switches differ from its line's (an arm-0 line re-run after the flip")
    say("  records the fixes ON), and its head rule binds the screen head 21b3b857.")
    say("")
    # ---- simulation python files
    simpy = {}
    for n in names(HERE):
        if n.endswith(".py"):
            text = read(os.path.join(HERE, n))
            if SIM_RE.search(text):
                simpy[n] = sets_both(text)
    # ---- B. runners
    runners = [n for n in names(HERE) if n.endswith((".sh", ".ps1"))]
    say("B. RUNNERS (outputs/*.sh, outputs/*.ps1, %d files)" % len(runners))
    cnt = collections.Counter()
    for n in runners:
        text = read(os.path.join(HERE, n))
        kinds = [k for pat, k in LAUNCH if pat in text]
        for py in sorted(set(re.findall(r"([A-Za-z0-9_./-]+\.py)\b", text))):
            base = os.path.basename(py)
            if base in simpy and base not in kinds:
                kinds.append(base)
        cls = "NOT-A-SIMULATION" if not kinds else ("FLIP-SAFE" if sets_both(text) else "SILENT-CHANGE")
        cnt[cls] += 1
        say("  %-40s %-18s %s" % (n, cls, ",".join(kinds) or "-"))
    say("  " + ", ".join("%s %d" % kv for kv in sorted(cnt.items())))
    say("")
    # ---- C. entry points
    say("C. ENTRY POINTS AND THE SUITE")
    for n in names(ROOT):
        if n.endswith(".py") and n not in NOT_ENTRY and SIM_RE.search(read(os.path.join(ROOT, n))):
            say("  %-40s runs the model -> the SHIPPED values (intended: this is the ship)" % n)
    say("  tests/ (the suite)                       run on the flipped tree; today's movement tests pin both fixes to")
    say("                                           0 with ON counterparts (outputs/mvg_report.txt 11.2 (d))")
    say("")
    outpy = sorted(simpy.items())
    say("D. PYTHON IN outputs/ THAT RUNS THE MODEL (non-recursive: %d files)" % len(outpy))
    say("  FLIP-SAFE (names both flipped keys) %d, SILENT-CHANGE %d:" % (sum(1 for _n, s in outpy if s),
                                                                       sum(1 for _n, s in outpy if not s)))
    for n, s in outpy:
        say("  %-44s %s" % (n, "FLIP-SAFE" if s else "SILENT-CHANGE"))
    say("  (the harnesses and probes pass the queue line's --set through; their meaning is the line's, A / A2)")
    say("")
    say("WHAT TO DO BEFORE RE-RUNNING ANY SILENT-CHANGE LINE: add --set FF_APPROACH_PATH=0")
    say("--set FF_RETREAT_KEEP_APPROACH=0 to reproduce its recorded pre-flip meaning (the base movement exactly). The")
    say("recorded runs themselves are unaffected (they are files); only a re-run changes meaning.")
    with open(OUT + ".tmp", "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    os.replace(OUT + ".tmp", OUT)
    print("wrote %s: %d queue files (%d SILENT-CHANGE lines), %d pool queues, %d runners" % (
        os.path.basename(OUT), len(rows), tot["silent"], len(jrows), len(runners)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
